GET http://localhost:3000/users

POST http://localhost:3000/users
content-type: application/json

{
    "email":"bot002@example.com",
    "password":"12345678"
}

PUT http://localhost:3000/users/4
content-type: application/json

{
    "email":"bot00111@example.com",
    "password":"987654321"
}

DELETE http://localhost:3000/users/5