GET http://localhost:3000/products

POST http://localhost:3000/products
content-type: application/json

{
    "productname":"Cookies",
    "exp_date":"2019-5-10"
}

PUT http://localhost:3000/products/1
content-type: application/json

{
    "productname":"Leche Evaporada",
    "exp_date":"2019-10-10"
}

DELETE http://localhost:3000/products/2